export const CHECK_TOKEN_STATUS = 'CHECK_TOKEN_STATUS';
export const SET_DRONE_DEPLOY_API = 'SET_DRONE_DEPLOY_API';
export const EXPORT_IMAGE = 'EXPORT_IMAGE';
export const EXPORT_IMAGE_SUCCEEDED = 'EXPORT_IMAGE_SUCCEEDED';
export const EXPORT_IMAGE_FAILED = 'EXPORT_IMAGE_FAILED';
