export const CHECK_TOKEN_STATUS = 'CHECK_TOKEN_STATUS';
export const CALL_API = 'CALL_API';
export const SEND_TEST_CALL = 'SEND_TEST_CALL';
export const SEND_TEST_CALL_SUCCEEDED = 'SEND_TEST_CALL_SUCCEEDED';
export const SEND_TEST_CALL_FAILED = 'SEND_TEST_CALL_FAILED';
